[tool.poetry]
name = "vrepo"
version = "0.1.0"
description = ""
authors = ["tranvu <<>>"]

[tool.poetry.dependencies]
python = "^3.8"
pexpect = "^4.8.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
